apiVersion: v1
kind: Service
metadata:
  name: my-svc
  namespace: apps
  labels:
    run: my-svc
spec:
  type: ClusterIP
  externalIPs: 
    - 80.12.11.13
  ports:
  - name: http
    port: 9009
    protocol: TCP
  selector:
    run: my-svc